routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::group(['middleware' => ['role:admin']], function () {
		Route::resource('category', 'CategoryController');
		Route::resource('product', 'ProductController');
		Route::resource('user', 'UserController');
	});

	Route::group(['middleware' => ['role:kasir|admin']], function () {
		Route::get('/pos', 'PosController@index')->name('pos.index');
		Route::post('/pos', 'PosController@store')->name('pos.store');
		Route::get('/pos/reset', 'PosController@reset')->name('pos.reset');	
	});

	Route::group(['middleware' => ['role:owner|admin']], function () {
		Route::get('product/print/all', 'ProductController@print')->name('product.print');
		Route::get('/pos/print-all', 'PosController@printAll')->name('pos.printAll');
	});

	Route::group(['middleware' => ['role:owner|admin|kasir']], function () {
		Route::get('/pos/list', 'PosController@list')->name('pos.list');
		Route::get('/pos/print/{id}', 'PosController@print')->name('pos.print');
	});

	Route::post('/change-password', 'HomeController@changePassword')->name('change-password');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $fillable = [
		'name',
		'category_id',
		'price',
		'description',
		'image',
	];

	public function category()
	{
		return $this->hasOne('App\Category', 'id', 'category_id');
	}

	public function pos()
	{
		return $this->belongsTo('App\PosDetail', 'product_id', 'id');
	}
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use PDF;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
			$product = Product::orderBy('name', 'ASC')->get();
			return view('product.index', compact('product'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
			$category = Category::orderBy('name', 'ASC')->get();
			return view('product.create', compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
			$this->validate($request, [
				'name' => 'required|string',
				'category_id' => 'required|string|exists:categories,id',
				'price' => 'required|numeric',
				'description' => 'required|string',
				'image' => 'nullable|file'
			]);
			try {
				$file = '';
				if ($request->hasFile('image')) {
					$name = $request->name . '-' . rand(1000, 9999) . '.' . $request->image->getClientOriginalExtension();
					$path = $request->file('image')->storeAs('product', $name, 'images');
					$file = $name;
				}

				$product = Product::firstOrCreate([
					'name' => $request->name,
					'category_id' => $request->category_id,
					'price' => $request->price,
					'description' => $request->description,
					'image' => $file
				]);

				session()->flash('success', 'Data Produk di-Tambahkan !');
				return redirect(route('product.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back()->withInput();
			}
		}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
			try {
				$edit = Product::findOrFail($id);
				$category = Category::orderBy('name', 'ASC')->get();

				return view('product.edit', compact('edit', 'category'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
			$this->validate($request, [
				'name' => 'required|string',
				'category_id' => 'required|string|exists:categories,id',
				'price' => 'required|numeric',
				'description' => 'required|string',
				'image' => 'nullable|file'
			]);

			try {
				$product = Product::findOrFail($id);

				$file = '';
				if ($request->hasFile('image')) {
					Storage::disk('images')->delete('product/' . $product->image);
					$name = $request->name . '-' . rand(1000, 9999) . '.' . $request->image->getClientOriginalExtension();
					$path = $request->file('image')->storeAs('product', $name, 'images');
					$file = $name;
				} else {
					$file = $product->image;
				}

				$product->update([
					'name' => $request->name,
					'category_id' => $request->category_id,
					'price' => $request->price,
					'description' => $request->description,
					'image' => $file
				]);

				session()->flash('info', 'Data Produk di-Ubah !');
				return redirect(route('product.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
			try {
				$product = Product::findOrFail($id);
				Storage::disk('images')->delete('product/' . $product->image);
				$product->delete();

				session()->flash('warning', 'Data Produk di-Hapus !');
				return redirect(route('product.index'));
			} catch (\Exception $e) {
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}

		public function print()
		{
			try {
				$product = Product::orderBy('name', 'ASC')->get();
				$pdf = PDF::loadview('product.print', compact('product'));
				return $pdf->stream('product-pdf');
			} catch (\Exception $e) {
				dd($e);
				session()->flash('error', 'Terjadi Kesalahan !');
				return redirect()->back();
			}
		}
}

resources/views/product/create.blade.php
@extends('layouts.master')

@section('content')
<div class="col-12">
  <div class="card card-outline card-primary">
    <div class="card-header">
      <h5 class="card-title">Form Tambah Produk</h5>
      <div class="card-tools">
        <a href="{{ route('product.index') }}" class="btn btn-xs btn-danger">
          &ensp; <i class="fa fa-arrow-left"></i> &ensp;
          Kembali
        </a>
      </div>
    </div>
    <div class="card-body">
      <form action="{{ route('product.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="row">
          <div class="col-md-8 col-lg-8">
            <div class="form-group">
              <label for="" class="form-control-label">Nama Produk : </label>
              <input type="text" name="name" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" placeholder="Masukan Nama Produk..." value="{{ old('name') }}" required autofocus>
              <span class="invalid-feedback">
                {{ $errors->first('name') }}
              </span>
            </div>
          </div>
          <div class="col-md-4 col-lg-4">
            <div class="form-group">
              <label for="" class="form-control-label">Kategori Produk : </label>
              <select name="category_id" id="category_id" class="form-control" required>
								<option value="">Pilih Kategori</option>
								@foreach ($category as $item)
									<option value="{{ $item->id }}" {{ $item->id == old('category_id') ? 'selected':'' }}>{{ $item->name }}</option>
								@endforeach
              </select>
              <span class="invalid-feedback">
                {{ $errors->first('category_id') }}
              </span>
            </div>
          </div>
          <div class="col-md-12 col-lg-12">
            <div class="form-group">
              <label for="" class="form-control-label">Deskripsi Produk : </label>
              <textarea name="description" id="description" rows="2" class="form-control" placeholder="Masukan Deskripsi Produk" required>{{ old('description') }}</textarea>
              <span class="invalid-feedback">
                {{ $errors->first('name') }}
              </span>
            </div>
          </div>
          <div class="col-md-8 col-lg-8">
            <div class="form-group">
              <label for="image">Foto Produk : </label>
              <div class="input-group">
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="image" name="image" value="{{ old('image') }}">
                  <label class="custom-file-label" id="text-image" for="image">Pilih Foto</label>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4 col-lg-4">
            <div class="form-group">
              <label for="">Harga Produk : </label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">Rp. </span>
                </div>
                <input type="number" name="price" id="price" class="form-control" value="{{ old('price') }}" required min="0" placeholder="0">
              </div>
            </div>
          </div>
          <div class="col-md-2 col-lg-2">
            <div class="form-group">
              <button type="submit" class="btn btn-success btn-sm btn-block">
                <i class="fa fa-check"></i> &ensp;
                Tambah Data
              </button>
            </div>
          </div>
          <div class="col-md-2 col-lg-2">
            <div class="form-group">
              <button type="submit" class="btn btn-danger btn-sm btn-block">
                <i class="fa fa-undo"></i> &ensp;
                Reset Input
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function() {
		$('#image').on('change', function() {
			$('#text-image').text(this.files && this.files.length ? this.files[0].name : 'Pilih Foto');
		});
	});
</script>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="col-12">
  <div class="card card-outline card-primary">
    <div class="card-header">
      <h5 class="card-title">Form Edit Produk</h5>
      <div class="card-tools">
        <a href="{{ route('product.index') }}" class="btn btn-xs btn-danger">
          &ensp; <i class="fa fa-arrow-left"></i> &ensp;
          Kembali
        </a>
      </div>
    </div>
    <div class="card-body">
      <form action="{{ route('product.update', $edit->id) }}" method="post" enctype="multipart/form-data">
				@csrf
				@method('PUT')
        <div class="row">
          <div class="col-md-8 col-lg-8">
            <div class="form-group">
              <label for="" class="form-control-label">Nama Produk : </label>
              <input type="text" name="name" id="name" class="form-control {{ $errors->has('name') ? 'is-invalid':'' }}" placeholder="Masukan Nama Produk..." value="{{ $edit->name }}" required autofocus>
              <span class="invalid-feedback">
                {{ $errors->first('name') }}
              </span>
            </div>
          </div>
          <div class="col-md-4 col-lg-4">
            <div class="form-group">
              <label for="" class="form-control-label">Kategori Produk : </label>
              <select name="category_id" id="category_id" class="form-control" required>
								<option value="">Pilih Kategori</option>
								@foreach ($category as $item)
									<option value="{{ $item->id }}" {{ $item->id == $edit->category_id ? 'selected':'' }}>{{ $item->name }}</option>
								@endforeach
              </select>
              <span class="invalid-feedback">
                {{ $errors->first('category_id') }}
              </span>
            </div>
          </div>
          <div class="col-md-12 col-lg-12">
            <div class="form-group">
              <label for="" class="form-control-label">Deskripsi Produk : </label>
              <textarea name="description" id="description" rows="2" class="form-control" placeholder="Masukan Deskripsi Produk" required>{{ $edit->description }}</textarea>
              <span class="invalid-feedback">
                {{ $errors->first('name') }}
              </span>
            </div>
          </div>
          <div class="col-md-8 col-lg-8">
            <div class="form-group">
              <label for="image">Foto Produk : </label>
              <div class="input-group">
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="image" name="image">
                  <label class="custom-file-label" id="text-image" for="image">Pilih Foto</label>
                </div>
							</div>
							Foto Saat Ini &ensp; : &ensp;
							<a href="{{ asset('upload') }}/product/{{ $edit->image }}" target="_blank">
								{{ $edit->image }}
							</a>
            </div>
          </div>
          <div class="col-md-4 col-lg-4">
            <div class="form-group">
              <label for="">Harga Produk : </label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="">Rp. </span>
                </div>
                <input type="number" name="price" id="price" class="form-control" value="{{ $edit->price }}" required min="0" placeholder="0">
              </div>
            </div>
          </div>
          <div class="col-md-2 col-lg-2">
            <div class="form-group">
              <button type="submit" class="btn btn-success btn-sm btn-block">
                <i class="fa fa-check"></i> &ensp;
                Tambah Data
              </button>
            </div>
          </div>
          <div class="col-md-2 col-lg-2">
            <div class="form-group">
              <button type="submit" class="btn btn-danger btn-sm btn-block">
                <i class="fa fa-undo"></i> &ensp;
                Reset Input
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
	$(document).ready(function() {
		$('#image').on('change', function() {
			$('#text-image').text(this.files && this.files.length ? this.files[0].name : 'Pilih Foto');
		});
	});
</script>
@endsection

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
<div class="col-12">
  <div class="card card-outline card-primary">
    <div class="card-header">
      <h5 class="card-title">
        Data Produk
      </h5>
      <div class="card-tools">
				<a href="{{ route('product.print') }}" target="_blank" class="btn btn-xs btn-success">
					<i class="fa fa-print"></i> &ensp; Print Data
				</a>
				<a href="{{ route('product.create') }}" class="btn btn-xs btn-primary"> &ensp; <i class="fa fa-plus"></i> &ensp; Tambah Data Produk</a>
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered table-hover" id="category-table">
          <thead>
            <tr>
              <th>Nama Produk</th>
              <th>Kategori</th>
              <th width="40%">Deskripsi</th>
              <th>Harga</th>
              <th class="text-center">Aksi</th>
            </tr>
          </thead>
          <tbody>
						@forelse ($product as $item)
							<tr>
								<td>{{ $item->name }}</td>
								<td>{{ $item->category->name }}</td>
								<td>{{ $item->description }}</td>
								<td>Rp. {{ number_format($item->price, 0, ',', '.') }}</td>
								<td width="10%" class="text-center">
									<div class="btn-group">
										<a href="{{ route('product.edit', $item->id) }}" class="btn btn-sm btn-warning">
											<i class="fa fa-edit"></i>
										</a>
										<form action="{{ route('product.destroy', $item->id) }}" method="post">
											@csrf
											@method('DELETE')
											<button type="submit" class="btn btn-sm btn-danger">
												<i class="fa fa-trash"></i>
											</button>
										</form>
									</div>
								</td>
							</tr> 
						@empty
							<tr>
								<td class="text-center" colspan="5">
									<h5>Belum Ada Data</h5>
								</td>
							</tr>
						@endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

@section('script')
<script>
  $(document).ready(function() {
    $('#category-table').DataTable({
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@endsection

resources/views/product/print.blade.php
<style>
	.order {
			font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
			border-collapse: collapse;
			width: 100%;
	}

	h4 {
		font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
	}

	.order td, .order th {
			border: 1px solid #ddd;
			padding: 8px;
	}

	.header td, .header th {
			border: 0px !important;
			padding: 8px;
	}

	.order tr:nth-child(even){background-color: #f2f2f2;}

	.order tr:hover {background-color: #ddd;}

	.order th {
			padding-top: 12px;
			padding-bottom: 12px;
			text-align: left;
			background-color: #4CAF50;
			color: white;
	}
</style>
<h4 style="text-align: center">
	Print Seluruh Daftar Produk
</h4>
<hr>
<table class="order header" width="100%">
	<tr>
		<td width="15%">Tanggal Print</td>
		<td width="5%">:</td>
		<td>{{ date('d/m/Y') }}</td>
		<td></td>
		<td width="15%">Pengguna</td>
		<td width="5%">:</td>
		<td>{{ ucwords(auth()->user()->name) }}</td>
	</tr>
</table>
<br>
<table class="order" width="100%">
	<thead>
		<tr>
			<td>Nama</td>
			<td>Kategori</td>
			<td>Harga</td>
			<td>Deskripsi</td>
		</tr>
	</thead>
	<tbody>
		@foreach ($product as $item)
			<tr>
				<td>{{ $item->name }}</td>
				<td>{{ $item->category->name }}</td>
				<td>Rp. {{ number_format($item->price, 0, ',', '.') }}</td>
				<td>{{ $item->description }}</td>
			</tr>
		@endforeach
	</tbody>
</table>