routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::group(['middleware' => ['role:admin']], function () {
		Route::resource('category', 'CategoryController');
		Route::resource('product', 'ProductController');
		Route::resource('user', 'UserController');
	});

	Route::group(['middleware' => ['role:kasir|admin']], function () {
		Route::get('/pos', 'PosController@index')->name('pos.index');
		Route::post('/pos', 'PosController@store')->name('pos.store');
		Route::get('/pos/reset', 'PosController@reset')->name('pos.reset');	
	});

	Route::group(['middleware' => ['role:owner|admin']], function () {
		Route::get('product/print/all', 'ProductController@print')->name('product.print');
		Route::get('/pos/print-all', 'PosController@printAll')->name('pos.printAll');
	});

	Route::group(['middleware' => ['role:owner|admin|kasir']], function () {
		Route::get('/pos/list', 'PosController@list')->name('pos.list');
		Route::get('/pos/print/{id}', 'PosController@print')->name('pos.print');
	});

	Route::post('/change-password', 'HomeController@changePassword')->name('change-password');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/master-pos.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>Cafe Holiday</title>

    <link rel="stylesheet" href="{{ asset('assets') }}/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="{{ asset('assets') }}/dist/css/adminlte.min.css">
    <link href="{{ asset('assets') }}/css/SourceSansPro.css" rel="stylesheet">


		@yield('css')
		@livewireStyles
</head>

<body class="hold-transition layout-top-nav">
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand-md navbar-dark navbar-navy">
            <div class="container">
                <a href="{{ route('home') }}" class="navbar-brand">
                    <img src="{{ asset('images') }}/baseImage/logo.png" alt="AdminLTE Logo"
                        class="brand-image img-circle elevation-3" style="opacity: .8">
                    <span class="brand-text font-weight-light">Cafe Holiday</span>
                </a>

                <button class="navbar-toggler order-1" type="button" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{{ route('home') }}" class="nav-link">Beranda</a>
                        </li>
                    </ul>
                </div>

                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link" data-toggle="dropdown" href="#">
                            <i class="fa fa-user"></i> &ensp;
                            {{ auth()->user()->name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <span class="dropdown-item dropdown-header">
                                <h5>Cafe Holiday</h5>
                                <img src="{{ asset('images') }}/baseImage/logo.png" alt="RestoLogo"
                                    class="brand-image img-fluid img-circle elevation-3"
                                    style="height: 100px !important;">
                            </span>
                            <div class="dropdown-divider"></div>
                            <a href="#" class="dropdown-item text-center">
                                Halo, {{ auth()->user()->name }}
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                                class="dropdown-item dropdown-footer">Logout</a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="content-wrapper"> 
            <div class="content">
                <div class="container">
                    <div class="row">
                      @yield('content')
                    </div>
                </div>
            </div>
        </div>
  

        <footer class="main-footer"> 
            <div class="float-right d-none d-sm-block">
              <b>Version</b> 1.0.0
            </div>
            <strong>Copyright &copy; 2020 <a href="http://adminlte.io">Cafe Holiday</a>.</strong> All rights
            reserved.
        </footer>
    </div>


    <script src="{{ asset('assets') }}/plugins/jquery/jquery.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('assets') }}/dist/js/adminlte.min.js"></script>

		@yield('script')
		@livewireScripts
</body>

</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Cafe Holiday</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ asset('assets') }}/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="{{ asset('assets') }}/css/ionicons.min.css">
    <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('assets') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('assets') }}/dist/css/adminlte.min.css">
    <link href="{{ asset('assets') }}/css/SourceSansPro.css" rel="stylesheet">

		<!-- Toastr -->
		<link rel="stylesheet" href="{{ asset('assets') }}/plugins/toastr/toastr.min.css">
	
		@yield('css')
</head>

<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-dark navbar-navy">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="fa fa-user"></i> &ensp;
                        {{ auth()->user()->name }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">
                            <h5>Cafe Holiday</h5>
                            <img src="{{ asset('images') }}/baseImage/logo.png" alt="RestoLogo"
                                class="brand-image img-fluid img-circle elevation-3" style="height: 100px !important;">
                        </span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item text-center">
                            Halo, {{ auth()->user()->name }}
                        </a>
												<div class="dropdown-divider"></div>
												<a href="#" class="dropdown-item dropdown-footer" data-toggle="modal" data-target="#change-password">Ganti Password</a>
                        <div class="dropdown-divider"></div>
                        <a href="{{ route('logout') }}"
													onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
													class="dropdown-item dropdown-footer">Logout</a>
												<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
													@csrf
												</form>
                    </div>
                </li>
            </ul>
        </nav>

        <aside class="main-sidebar elevation-4 sidebar-light-navy">
            <a href="{{ route('home') }}" class="brand-link">
                <img src="{{ asset('images') }}/baseImage/logo.png" alt="RestoLogo"
                    class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">&ensp; Cafe Holiday</span>
            </a>

            <div class="sidebar">

                @include('layouts.sidebar')
            </div>
        </aside>

        <div class="content-wrapper">
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>
                                {{ isset($title) ? $title : 'Cafe Holiday' }} <small style="font-size: 13px;"> | ver 1.0-1 </small>
                            </h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="home">Beranda</a></li>
                                <li class="breadcrumb-item active">Cafe Holiday</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </section>

            <section class="content">
                <div class="row">
                    @yield('content')
                </div>
            </section>
        </div>
        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 1.0.0
            </div>
            <strong>Copyright &copy; 2020 <a href="#">Cafe Holiday</a>.</strong> All rights
            reserved.
        </footer>

        <aside class="control-sidebar control-sidebar-dark">
        </aside>
		</div>

		<form action="{{ route('change-password') }}" method="post">
			@csrf
			<div class="modal fade" id="change-password" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="exampleModalLabel">Ganti Password</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<div class="row">
								<div class="col-12">
									<div class="form-group">
										<label for="">Password Lama : </label>
										<input type="password" name="old_password" id="old_password" class="form-control" placeholder="Masukan Password Lama..." required>
									</div>
									<div class="form-group">
										<label for="">Password Baru : </label>
										<input type="password" name="password" id="password" class="form-control" placeholder="Masukan Password Baru..." required>
									</div>
									<div class="form-group">
										<label for="">Tulis Ulang Password Baru : </label>
										<input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Masukan Password Lama..." required>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<button type="reset" class="btn btn-danger" data-dismiss="modal">Tutup / Reset</button>
							<button type="submit" class="btn btn-success">Ubah Password</button>
						</div>
					</div>
				</div>
			</div>
		</form>


    <script src="{{ asset('assets') }}/plugins/jquery/jquery.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{ asset('assets') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
		<script src="{{ asset('assets') }}/dist/js/adminlte.min.js"></script>
		

		<!-- Toastr -->
		<script src="{{ asset('assets') }}/plugins/toastr/toastr.min.js"></script>

		@if (session()->has('success'))
		<script>
			toastr.success("{{ session('success') }}", 'Berhasil !');
		</script>
		@endif

		@if (session()->has('warning'))
		<script>
			toastr.warning("{{ session('warning') }}", 'Peringatan !');
		</script>
		@endif

		@if (session()->has('info'))
		<script>
			toastr.info("{{ session('info') }}", 'Informasi !');
		</script>
		@endif

		@if (session()->has('error'))
		<script>
			toastr.error("{{ session('error') }}", 'Kesalahan !');
		</script>
		@endif

		@yield('script')
</body>

</html>

resources/views/layouts/sidebar.blade.php
<nav class="mt-3">
    <ul class="nav nav-pills nav-sidebar flex-column nav-legacy" data-widget="treeview" role="menu"
        data-accordion="false">
        <li class="nav-item">
            <a href="{{ route('home') }}" class="nav-link">
                <i class="nav-icon fa fa-home"></i>
                <p>Dashboard</p>
            </a>
				</li>
				@if (auth()->user()->roles->first()->name == 'admin')
        <li class="nav-header" style="padding-top: 15px;">Master Data</li>
        <li class="nav-item">
            <a href="{{ route('category.index') }}" class="nav-link">
                <i class="nav-icon fa fa-edit"></i>
                <p>
                    Kategori
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('product.index') }}" class="nav-link">
                <i class="nav-icon fa fa-edit"></i>
                <p>
                    Produk
                </p>
            </a>
				</li>
				@endif
				
				@if (auth()->user()->roles->first()->name == 'kasir' || auth()->user()->roles->first()->name == 'admin')
        <li class="nav-header" style="padding-top: 10px;">Transaksi</li>
        <li class="nav-item">
            <a href="{{ route('pos.index') }}" class="nav-link">
                <i class="nav-icon fa fa-shopping-cart"></i>
                <p> Kasir</p>
            </a>
				</li>
				@endif
				
				<li class="nav-header" style="padding-top: 10px;">Laporan</li>
				@if (auth()->user()->roles->first()->name == 'admin' || auth()->user()->roles->first()->name == 'kasir' || auth()->user()->roles->first()->name == 'owner')
        <li class="nav-item">
            <a href="{{ route('pos.list') }}" class="nav-link">
                <i class="nav-icon fa fa-cubes"></i>
                <p>Data Penjualan</p>
            </a>
        </li>
				@endif
				@if (auth()->user()->roles->first()->name == 'admin' || auth()->user()->roles->first()->name == 'owner')
        <li class="nav-item">
            <a href="{{ route('product.print') }}" target="_blank" class="nav-link">
                <i class="nav-icon fa fa-cubes"></i>
                <p>Data Produk</p>
            </a>
				</li>
				@endif
				@if (auth()->user()->roles->first()->name == 'admin')				
        <li class="nav-header" style="padding-top: 10px;">Lainnya</li>
        <li class="nav-item">
            <a href="{{ route('user.index') }}" class="nav-link">
                <i class="nav-icon fa fa-users text-pink"></i>
                <p>Master Pengguna</p>
            </a>
				</li>
				@endif
    </ul>
</nav>